CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    login_id VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    university VARCHAR(255) NOT NULL,
    major VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    authority INTEGER NOT NULL,
    profile VARCHAR(255),
    view INTEGER NOT NULL
);

CREATE TABLE users_roles (
    users_id BIGINT NOT NULL,
    roles VARCHAR(255),
    CONSTRAINT fk_users_roles_users FOREIGN KEY (users_id) REFERENCES users (id)
);

CREATE TABLE contest (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    authority BIGINT NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    simple_info VARCHAR(255),
    problem_info VARCHAR(255),
    contest_host BIGINT,
    solution BYTEA
);

CREATE TABLE contestant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_checked BOOLEAN,
    users_id BIGINT NOT NULL,
    CONSTRAINT fk_contestant_users FOREIGN KEY (users_id) REFERENCES users (id)
);

CREATE TABLE contestant_contest (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contestant_id BIGINT NOT NULL,
    contest_id BIGINT NOT NULL,
    CONSTRAINT fk_contestant_contest_contestant FOREIGN KEY (contestant_id) REFERENCES contestant (id),
    CONSTRAINT fk_contestant_contest_contest FOREIGN KEY (contest_id) REFERENCES contest (id)
);

CREATE TABLE examiner (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id BIGINT NOT NULL,
    contest_id BIGINT NOT NULL,
    CONSTRAINT fk_examiner_users FOREIGN KEY (users_id) REFERENCES users (id),
    CONSTRAINT fk_examiner_contest FOREIGN KEY (contest_id) REFERENCES contest (id)
);

CREATE TABLE problem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number VARCHAR(255),
    title VARCHAR(255),
    content VARCHAR(255),
    input VARCHAR(255),
    output VARCHAR(255),
    time_limit VARCHAR(255),
    score INTEGER NOT NULL,
    contest_id BIGINT,
    CONSTRAINT fk_problem_contest FOREIGN KEY (contest_id) REFERENCES contest (id)
);

CREATE TABLE io (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    input VARCHAR(255),
    output VARCHAR(255),
    problem_id BIGINT NOT NULL,
    CONSTRAINT fk_io_problem FOREIGN KEY (problem_id) REFERENCES problem (id)
);

CREATE TABLE problem_image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url VARCHAR(255),
    problem_id BIGINT NOT NULL,
    CONSTRAINT fk_problem_image_problem FOREIGN KEY (problem_id) REFERENCES problem (id)
);

CREATE TABLE submit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language VARCHAR(255) NOT NULL,
    runtime BIGINT NOT NULL,
    memo_limit BIGINT NOT NULL,
    code VARCHAR(255) NOT NULL,
    time TIMESTAMP NOT NULL,
    result BIGINT,
    users_id BIGINT NOT NULL,
    problem_id BIGINT NOT NULL,
    contest_id BIGINT NOT NULL,
    CONSTRAINT fk_submit_users FOREIGN KEY (users_id) REFERENCES users (id),
    CONSTRAINT fk_submit_problem FOREIGN KEY (problem_id) REFERENCES problem (id),
    CONSTRAINT fk_submit_contest FOREIGN KEY (contest_id) REFERENCES contest (id)
);

CREATE TABLE contest_notice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content VARCHAR(255) NOT NULL,
    time TIMESTAMP NOT NULL,
    contest_id BIGINT NOT NULL,
    users_id BIGINT NOT NULL,
    CONSTRAINT fk_contest_notice_contest FOREIGN KEY (contest_id) REFERENCES contest (id),
    CONSTRAINT fk_contest_notice_users FOREIGN KEY (users_id) REFERENCES users (id)
);

CREATE TABLE contest_question (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question VARCHAR(255) NOT NULL,
    content VARCHAR(255) NOT NULL,
    question_time TIMESTAMP NOT NULL,
    answer VARCHAR(255),
    answer_time TIMESTAMP,
    questioner_id BIGINT,
    answerer_id BIGINT,
    contest_id BIGINT,
    CONSTRAINT fk_contest_question_questioner FOREIGN KEY (questioner_id) REFERENCES users (id),
    CONSTRAINT fk_contest_question_answerer FOREIGN KEY (answerer_id) REFERENCES users (id),
    CONSTRAINT fk_contest_question_contest FOREIGN KEY (contest_id) REFERENCES contest (id)
);

CREATE TABLE menu_notice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    content VARCHAR(255),
    time TIMESTAMP,
    users_id BIGINT NOT NULL,
    CONSTRAINT fk_menu_notice_users FOREIGN KEY (users_id) REFERENCES users (id)
);

CREATE TABLE menu_question (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content VARCHAR(255) NOT NULL,
    time TIMESTAMP NOT NULL,
    users_id BIGINT NOT NULL,
    CONSTRAINT fk_menu_question_users FOREIGN KEY (users_id) REFERENCES users (id)
);

CREATE TABLE menu_comment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content VARCHAR(255),
    time TIMESTAMP,
    users_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    CONSTRAINT fk_menu_comment_users FOREIGN KEY (users_id) REFERENCES users (id),
    CONSTRAINT fk_menu_comment_question FOREIGN KEY (question_id) REFERENCES menu_question (id)
);

CREATE INDEX idx_users_roles_users_id ON users_roles (users_id);
CREATE INDEX idx_contestant_users_id ON contestant (users_id);
CREATE INDEX idx_contestant_contest_contestant_id ON contestant_contest (contestant_id);
CREATE INDEX idx_contestant_contest_contest_id ON contestant_contest (contest_id);
CREATE INDEX idx_examiner_users_id ON examiner (users_id);
CREATE INDEX idx_examiner_contest_id ON examiner (contest_id);
CREATE INDEX idx_problem_contest_id ON problem (contest_id);
CREATE INDEX idx_io_problem_id ON io (problem_id);
CREATE INDEX idx_problem_image_problem_id ON problem_image (problem_id);
CREATE INDEX idx_submit_users_id ON submit (users_id);
CREATE INDEX idx_submit_problem_id ON submit (problem_id);
CREATE INDEX idx_submit_contest_id ON submit (contest_id);
CREATE INDEX idx_contest_notice_contest_id ON contest_notice (contest_id);
CREATE INDEX idx_contest_notice_users_id ON contest_notice (users_id);
CREATE INDEX idx_contest_question_contest_id ON contest_question (contest_id);
CREATE INDEX idx_menu_notice_users_id ON menu_notice (users_id);
CREATE INDEX idx_menu_question_users_id ON menu_question (users_id);
CREATE INDEX idx_menu_comment_question_id ON menu_comment (question_id);
